blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ åŠ å…¥ QQ ç¾¤äº¤æµï¼ˆ1038047655ï¼‰
    url: https://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=2oA3p4PkON0BqPOQ8YmDfEEEFs3O-Qec&authKey=y7Wh6li8APK%2Bk5s3dkXTrdA%2FSZM1Q8eSIIE%2BlmEXd62YCjdfdQJOhNjnKIWo2%2BSH&noverify=0&group_code=1038047655
    about: æœ‰é—®é¢˜ä¹Ÿæ¬¢è¿åŠ å…¥ QQ ç¾¤æé—®äº¤æµï¼Œæˆ‘ä»¬ä¹äºå¸®åŠ©ä½ ã€‚
