blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ åŠ å…¥ QQ ç¾¤äº¤æµï¼ˆ1038047655ï¼‰
    url: https://qm.qq.com/cgi-bin/qm/qr?k=1038047655
    about: æœ‰é—®é¢˜ä¹Ÿæ¬¢è¿åŠ å…¥ QQ ç¾¤æé—®äº¤æµï¼Œæˆ‘ä»¬ä¹äºå¸®åŠ©ä½ ã€‚
